api_platform:
    swagger:
         api_keys:
             JWT:
                name: Authorization
                type: header
    title: 'SecretLife API'
    version: '1.0.0'
    enable_profiler: true